#!/bin/sh

interface="wlan0"
signal=$(sudo iw dev "$interface" link | grep -i signal | awk '{print $2}')

if [ -z "$signal" ]; then
  icon="󰤮"
else
  quality=$(( (signal + 100) * 100 / 70 ))
  case $quality in
    [0-10]) icon="󰤠" ;;
    [11-25]) icon="󰤢" ;;
    [26-50]) icon="󰤥" ;;
    [51-100]) icon="󰖩" ;;
  esac
fi

case $BLOCK_BUTTON in
  1)
    ssid=$(sudo iw dev "$interface" link | grep SSID | awk '{print $2}')
    local_ip=$(ip a show "$interface" | grep "inet " | awk '{print $2}')
    firewall_status=$(sudo ufw status | grep "Status:" | awk '{print $2}')
    notify-send "📶 $ssid" "Quality: $quality%\nLocal IP: $local_ip\nFirewall: $firewall_status"
    ;;
  2)
    public_ip=$(curl -s ifconfig.me)
    mac_address=$(ip link show "$interface" | awk '/link\/ether/ {print $2}')
    dns_servers=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}' | tr '\n' ' ')
    gateway_ip=$(ip route | grep default | awk '{print $3}')
    notify-send "🌐 Network Details" "Public IP: $public_ip\nMAC: $mac_address\nDNS: $dns_servers\nGateway: $gateway_ip"
    ;;
  6) st -e nvim "$0" ;;
esac

echo "$icon "
