#!/bin/bash

# Dependencies
deps=("yt-dlp" "fzf" "mpv")

# Check dependencies
check_failed=false
for dep in "${deps[@]}"; do
  if ! command -v "$dep" &>/dev/null; then
    echo "Error: $dep is not installed." >&2
    check_failed=true
  fi
done
if $check_failed; then
  exit 1
fi

# Configuration
search_size=10 # Reduced default

# Functions
get_video_url() {
  local query="$1"

  local results=$(yt-dlp -j --flat-playlist "ytsearch$search_size:$query" 2>/dev/null)

  if [[ -z "$results" ]]; then
    echo "No videos found."
    return 1
  fi

  local selection=$(echo "$results" | \
    jq -c '.' |
    fzf --height "40%" --reverse --header "Select video" --print0
  )

  if [[ -z "$selection" ]]; then
    echo "No video selected."
    return 1
  fi

  local url=$(echo "$selection" | xargs -0 jq -r '.url')

  echo "$url"
  return 0
}

play_video() {
  local url="$1"
  if [[ -n "$url" ]]; then
    mpv --really-quiet "$url" &
  fi
}

# Main
read -p "Enter search query: " query

if [[ -n "$query" ]]; then
  video_url=$(get_video_url "$query")
  if [[ -n "$video_url" ]]; then
    play_video "$video_url"
  fi
}
